### ISSUE TITLE
下载安装包后解压，运行出现报错，是不是因为缺少安装依赖？

### ISSUE THREAD

**Issue by niuyuxuan** [knownsec/pocsuite3#175]
Traceback (most recent call last):
  File "cli.py", line 12, in <module>
    from pocsuite3.lib.core.option import init
  File "/home/jiuan123/pocsuite3-master/pocsuite3/__init__.py", line 11, in <module>
    from .cli import module_path
  File "/home/jiuan123/pocsuite3-master/pocsuite3/cli.py", line 12, in <module>
    from pocsuite3.lib.core.option import init
  File "/home/jiuan123/pocsuite3-master/pocsuite3/lib/core/option.py", line 32, in <module>
    from pocsuite3.lib.request.patch import patch_all
  File "/home/jiuan123/pocsuite3-master/pocsuite3/lib/request/patch/__init__.py", line 6, in <module>
    from .hook_request import patch_session
  File "/home/jiuan123/pocsuite3-master/pocsuite3/lib/request/patch/hook_request.py", line 9, in <module>
    from requests.compat import OrderedDict, Mapping
ImportError: cannot import name 'Mapping'

**Comment by niuyuxuan** [comment]
我先自己解决一下
