### ISSUE TITLE
求助 运行时报错

### ISSUE THREAD

**Issue by fbw867294173** [knownsec/pocsuite3#297]
Traceback (most recent call last):
  File "D:\Python\Python39\Scripts\pocsuite-script.py", line 33, in <module>
    sys.exit(load_entry_point('pocsuite3==1.9.5', 'console_scripts', 'pocsuite')())
  File "D:\Python\Python39\Scripts\pocsuite-script.py", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "D:\Python\Python39\lib\importlib\metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "D:\Python\Python39\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "D:\Python\Python39\lib\site-packages\pocsuite3\__init__.py", line 10, in <module>
    from .lib.core.common import set_paths
  File "D:\Python\Python39\lib\site-packages\pocsuite3\lib\core\common.py", line 27, in <module>
    from pocsuite3.lib.core.data import conf
  File "D:\Python\Python39\lib\site-packages\pocsuite3\lib\core\data.py", line 2, in <module>
    from pocsuite3.lib.core.log import LOGGER
  File "D:\Python\Python39\lib\site-packages\pocsuite3\lib\core\log.py", line 25, in <module>
    FORMATTER = colorlog.LevelFormatter(
  File "D:\Python\Python39\lib\site-packages\colorlog\colorlog.py", line 160, in __init__
    super(LevelFormatter, self).__init__(
  File "D:\Python\Python39\lib\site-packages\colorlog\colorlog.py", line 91, in __init__
    super(ColoredFormatter, self).__init__(fmt, datefmt, style)
  File "D:\Python\Python39\lib\logging\__init__.py", line 574, in __init__
    self._style.validate()
  File "D:\Python\Python39\lib\logging\__init__.py", line 426, in validate
    if not self.validation_pattern.search(self._fmt):
TypeError: expected string or bytes-like object

**Comment by 13ph03nix** [comment]
使用什么方式安装的呢，看起来像是 `colorlog` 依赖库的问题，可以升级试试

`pip3 install --upgrade colorlog`
