### ISSUE TITLE
[bug] 报错：Exception: Invalid expression [!contains(tolower(body), '<html')], only a very simple subset of Python is allowed.

### ISSUE THREAD

**Issue by Arbor01** [knownsec/pocsuite3#342]
使用POC：https://github.com/projectdiscovery/nuclei-templates/blob/master/exposures/configs/git-config.yaml
版本：2.0.1
报错信息：
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/pocsuite3/lib/yaml/nuclei/protocols/common/expressions/__init__.py", line 842, in evaluate
    result = safe_eval(potential_match, variables)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/pocsuite3/lib/yaml/nuclei/protocols/common/expressions/safe_eval.py", line 216, in safe_eval
    raise Exception(f"Invalid expression [{expression}], only a very simple subset of Python is allowed.")
Exception: Invalid expression [!contains(tolower(body), '<html')], only a very simple subset of Python is allowed.

**Comment by 13ph03nix** [comment]
在执行表达式时，对非逻辑运算存在问题，`v2.0.2` 版本已修复 :)
