### ISSUE TITLE
windows下启动console.py报错

### ISSUE THREAD

**Issue by 0FuzzingQ** [knownsec/pocsuite3#37]
`C:\Users\aldin\Desktop\secmdb\pocsuite3-master\pocsuite3-master\pocsuite3>python3 console.py
Traceback (most recent call last):
  File "console.py", line 10, in <module>
    import pocsuite3
  File "C:\Program Files\Python36\lib\site-packages\pocsuite3\__init__.py", line 10, in <module>
    from .lib.core.common import set_paths
  File "C:\Program Files\Python36\lib\site-packages\pocsuite3\lib\core\common.py", line 22, in <module>
    from pocsuite3.lib.core.convert import stdout_encode
  File "C:\Program Files\Python36\lib\site-packages\pocsuite3\lib\core\convert.py", line 3, in <module>
    from pocsuite3.lib.core.settings import IS_WIN
  File "C:\Program Files\Python36\lib\site-packages\pocsuite3\lib\core\settings.py", line 10, in <module>
    REVISION = get_revision_number()
  File "C:\Program Files\Python36\lib\site-packages\pocsuite3\lib\core\revision.py", line 54, in get_revision_number
    match = re.search(r"(?i)[0-9a-f]{32}", stdout or "")
  File "C:\Program Files\Python36\lib\re.py", line 182, in search
    return _compile(pattern, flags).search(string)
TypeError: cannot use a string pattern on a bytes-like object`

解决办法：pocsuite3\lib\core\revision.py line55

stdout.decode('utf-8')

**Comment by boy-hack** [comment]
thanks
