### ISSUE TITLE
update错误

### ISSUE THREAD

**Issue by mgiftdc** [knownsec/pocsuite3#5]
pocsuite --update

                              ,--. ,--.
 ,---. ,---. ,---.,---.,--.,--`--,-'  '-.,---.  {1.2.0-nongit-20190318}
| .-. | .-. | .--(  .-'|  ||  ,--'-.  .-| .-. :
| '-' ' '-' \ `--.-'  `'  ''  |  | |  | \   --.
|  |-' `---' `---`----' `----'`--' `--'  `----'
`--'                                            http://pocsuite.org

[*] starting at 14:42:02

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/pocsuite3/cli.py", line 54, in main
    init()
  File "/usr/local/lib/python3.7/dist-packages/pocsuite3/lib/core/option.py", line 577, in init
    _set_pocs_modules()
  File "/usr/local/lib/python3.7/dist-packages/pocsuite3/lib/core/option.py", line 328, in _set_pocs_modules
    if not load_poc_sucess:
UnboundLocalError: local variable 'load_poc_sucess' referenced before assignment

[*] shutting down at 14:42:02

**Comment by FakeXing** [comment]
我也遇到了同样的问题
![image](https://user-images.githubusercontent.com/31611714/63640614-c14e2080-c6d4-11e9-9965-76f806ed9768.png)
